# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rehan Butt
email: me@rehanbutt.com
description: > # this means to ignore newlines until "baseurl:"
2021 Year in Review, Check back towards the end of the year for a look back at 2021
baseurl: "" # the subpath of your site, e.g. /blog
mainurl: "https://rehanbutt.com"
url: "https://2021.rehanbutt.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

plugins: [jekyll-sitemap]
